name: Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: yarn install, build
        run: |
          yarn install
          yarn build
        env:
          CI: false
          VITE_DONATION_ADDRESS: ${{ secrets.DONATION_ADDRESS }}
          VITE_NETWORK: mainnet
          VITE_ACCOUNT_MINTER_CONTRACT: "0xF8DcD4eE078A0E2e7AcadA12A00a5993CCE2a55D"
          VITE_FARM_CONTRACT: "0x2B4A66557A79263275826AD31a4cDDc2789334bD"
          VITE_SESSION_CONTRACT: "0x9314b4b16024729aD701b320839dbb04BE6812fd"
          VITE_INVENTORY_CONTRACT: "0x22d5f9B75c524Fec1D6619787e582644CD4D7422"
          VITE_TOKEN_CONTRACT: "0xD1f9c58e33933a993A3891F8acFe05a68E1afC05"
          VITE_WISHING_WELL_CONTRACT: "0x24d32a94fA91d4C99f994622AF30Eb16bf76AEAC"
          VITE_PAIR_CONTRACT: "0x6f9e92dd4734c168a734b873dc3db77e39552eb6"
          VITE_DISCORD_REDIRECT: "https://sunflower-land.com/play/"
          VITE_CLIENT_VERSION: ${{ steps.date.outputs.date }}
          VITE_RELEASE_VERSION: ${{ steps.get_version.outputs.VERSION }}
          VITE_RECAPTCHA_SITEKEY: "6Lfqm6MeAAAAAFS5a0vwAfTGUwnlNoHziyIlOl1s"
          VITE_CLOUDFLARE_CAPTCHA_SITEKEY: "0x4AAAAAAAAoLnsFOUvGeYp7"
          VITE_TRADER_CONTRACT: "0x1056A4ea959e3d84D6DC56Ac06B8Ff5B84648400"
          VITE_TREASURY_ADDRESS: "0x1DB57407EE80709D4d862fe81399FBB35B8B9586"
          VITE_FROG_CONTRACT: "0x52A5ddFF59E0A27a1cBA75c8045A434b7D296A6c"
          VITE_FROG_DONATION: "0xE3ac99Dc50fE9F0Ce9eCb5502399aee55F219448"
          VITE_TADPOLE_CONTRACT: "0xBFbF690E9D4929c95Ff63a38262fe6381d974D78"
          VITE_INCUBATOR_CONTRACT: "0x6aaD085B68CA1Cf01ac2AB0D2Bc814DE3b455EC1"
          VITE_WHITELIST_TOKEN_CONTRACT: "0x3f8a923DDa0C58ef6c353EFB8141007617Ab871c"

          VITE_BUMPKIN_DETAILS_CONTRACT: "0x687BcED586A8AECEdA5bd6b142577DE1d83a2a9c"
          VITE_BUMPKIN_ITEMS: "0x4bb5b2461e9Ef782152c3a96698b2a4cF55B6162"
          VITE_BUMPKIN_CONTRACT: "0x624E4fa6980Afcf8EA27BFe08e2fB5979b64DF1C"
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.8.x
          lhci autorun
